development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: Memphant_development
  pool: 5
  username: root
  password: qwerty
  socket: /var/run/mysqld/mysqld.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: Memphant_test
  pool: 5
  username: root
  password: qwerty
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: Memphant_production
  pool: 5
  username: root
  password: qwerty
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *TEST
